# Generated by Django 5.0.1 on 2024-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_id', models.CharField(max_length=255)),
                ('score', models.CharField(default=20080101, max_length=8)),
                ('favorite', models.CharField(default=20080101, max_length=8)),
                ('transfer_archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_id', models.BigIntegerField(default='请尽快绑定QQ号~')),
                ('group_real_user_id', models.CharField(max_length=100)),
                ('register_real_group_id', models.CharField(max_length=100)),
                ('nickname', models.CharField(default='请尽快更名~', max_length=255)),
                ('city', models.CharField(default='unknown', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('favorite', models.IntegerField(default=50)),
                ('avatar', models.URLField(default='https://naigos.cn/images/108202018_p3.jpg')),
                ('email', models.EmailField(default='绑定邮箱或申请奶果邮@naigos.cn', max_length=254)),
            ],
        ),
    ]
