# Generated by Django 5.0.1 on 2024-08-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
    ]
