# Generated by Django 5.0.1 on 2024-08-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_bots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
