# Generated by Django 5.0.1 on 2024-08-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_id', models.BigIntegerField()),
                ('group_real_user_id', models.TextField()),
                ('register_real_group_id', models.TextField()),
                ('nickname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('favorite', models.IntegerField(default=0)),
                ('avatar', models.URLField()),
                ('email', models.EmailField(default='请更新或申请奶果邮@naigos.cn', max_length=254)),
            ],
        ),
    ]
