# Generated by Django 5.0.1 on 2024-08-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group_real_user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='register_real_group_id',
            field=models.CharField(max_length=100),
        ),
    ]
