# Generated by Django 5.0.1 on 2024-08-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='password',
        ),
    ]
