# Generated by Django 5.0.1 on 2024-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_password_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='password',
            name='is_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='password',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
