# Generated by Django 5.0.1 on 2024-08-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_password_code_password_is_code_password_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='code',
        ),
        migrations.RemoveField(
            model_name='password',
            name='is_code',
        ),
    ]
