# Generated by Django 5.0.1 on 2024-08-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_password_code_remove_password_is_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
