# Generated by Django 5.0.1 on 2024-08-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='is_code',
            field=models.BooleanField(default=False),
        ),
    ]
