# Generated by Django 5.0.1 on 2024-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_password_is_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='expiration_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
