# Generated by Django 5.0.1 on 2024-08-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='bots',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='bots',
            name='safe_level',
        ),
    ]
