# Generated by Django 5.0.1 on 2024-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_remove_bots_access_token_remove_bots_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='password',
            field=models.TextField(default='<PASSWORD>'),
        ),
        migrations.AddField(
            model_name='bots',
            name='safe_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='bots',
            name='token',
            field=models.TextField(default='token'),
        ),
    ]
