# Generated by Django 5.0.3 on 2024-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sogouinputtheme',
            name='eject_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
