# Generated by Django 5.0.3 on 2024-08-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sogouinputtheme_eject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sogouinputtheme',
            name='theme_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
